In [1]:
import torch

#### At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array.

In [3]:
t1 = torch.tensor(4.0)

In [5]:
# data type
t1.dtype

torch.float32

In [8]:
t2 = torch.tensor([1., 2, 3 ,4])
t2

tensor([1., 2., 3., 4.])

In [10]:
t2.dtype
# note how dtype is float

torch.float32

In [11]:
# 3-dimensional array
t3 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

In [12]:
t3.dtype

torch.float32

In [13]:
t3.shape

torch.Size([2, 2, 3])

## Tensor Operations and Gradients

In [14]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [16]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

#### As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [19]:
y.backward()

In [22]:
w.grad

tensor(3.)

In [23]:
b.grad

tensor(1.)

## Interoperatibility with Numpy

In [24]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])

In [25]:
x_tensor = torch.from_numpy(x)

In [26]:
x_tensor

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [29]:
y = x_tensor.numpy()

In [30]:
y

array([[1., 2.],
       [3., 4.]])